# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170726_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=160)),
                ('event_detail', models.TextField()),
                ('event_pic', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('startdate_event', models.DateField(null=True)),
                ('enddate_event', models.DateField(null=True)),
            ],
        ),
    ]
