# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20170731_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startdate_event']},
        ),
    ]
