# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20170805_2220'),
    ]

    operations = [
    ]
